# Generated by Django 3.2.9 on 2021-12-02 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=10, unique=True)),
                ('pinCode', models.CharField(max_length=10)),
                ('row_created', models.DateTimeField(default=datetime.datetime.now)),
                ('row_last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=10, unique=True)),
                ('pinCode', models.CharField(max_length=10)),
                ('row_created', models.DateTimeField(default=datetime.datetime.now)),
                ('row_last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
